version: "3"

services:
    nextjs-client:
        build: .
        container_name: nextjs-client
        ports:
            - "80:3000"
        volumes:
            - .:/app
        environment:
            - TZ=Asia/Shanghai
        command: npm run start
        restart: always
