declare namespace PageRoute {
    /**
     * the root route key
     * @translate 根路由
     */
    type RootRouteKey = "root"

    /**
     * the not found route, which catch the invalid route path
     * @translate 未找到路由(捕获无效路径的路由)
     */
    type NotFoundRouteKey = "not-found"

    /**
     * the route key
     * @translate 页面路由
     */
    type RouteKey =
        | "/"
        | "index"
        | "403"
        | "404"
        | "500"
        | "not-found"
        | "docs"
        | "auth"
        | "auth_login"
        | "auth_register"
        | "dashboard"
        | "dashboard_analysis"
        | "dashboard_workbench"
        | "student"
        | "student_information"
        | "student_roll"
        | "student_attendance"
        | "teacher"
        | "teacher_information"
        | "teacher_work"
        | "teacher_attendance"
        | "course"
        | "course_setting"
        | "course_table"
        | "course_choose"
        | "score"
        | "score_enter"
        | "score_statistics"
        | "score_query"
        | "exam"
        | "exam_enter"
        | "exam_score"
        | "exam_query"
        | "task"
        | "task_add"
        | "task_send"
        | "task_correct"
        | "resource"
        | "resource_upload"
        | "resource_share"
        | "resource_online"
        | "activity"
        | "activity_release"
        | "activity_enroll"
        | "activity_achievement"
        | "class"
        | "class_member"
        | "class_forum"
        | "class_photo"
        | "learning"
        | "learning_classroom"
        | "learning_share"
        | "learning_discuss"
        | "notice"
        | "notice_school"
        | "notice_class"
        | "notice_person"
        | "setting"
        | "about"

    /**
     * last degree route key, which has the page file
     * @translate 最后一级路由(该级路有对应的页面文件)
     */
    type LastDegreeRouteKey = Extract<
        RouteKey,
        | "/"
        | "index"
        | "403"
        | "404"
        | "500"
        | "not-found"
        | "docs"
        | "auth_login"
        | "auth_register"
        | "about"
        | "dashboard_analysis"
        | "dashboard_workbench"
        | "student_information"
        | "student_roll"
        | "student_attendance"
        | "teacher_information"
        | "teacher_work"
        | "teacher_attendance"
        | "course_setting"
        | "course_table"
        | "course_choose"
        | "score_enter"
        | "score_statistics"
        | "score_query"
        | "exam_enter"
        | "exam_score"
        | "exam_query"
        | "task_add"
        | "task_send"
        | "task_correct"
        | "resource_upload"
        | "resource_share"
        | "resource_online"
        | "activity_release"
        | "activity_enroll"
        | "activity_achievement"
        | "class_member"
        | "class_forum"
        | "class_photo"
        | "learning_classroom"
        | "learning_share"
        | "learning_discuss"
        | "notice_school"
        | "notice_class"
        | "notice_person"
        | "setting"
        | "about"
    >
}
